apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data
spec:
  capacity:
    storage: 5Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.33.45
    path: "/opt/nfs/"
  mountOptions:
    - nfsvers=4.2