apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy_view_user
subjects:
- kind: User
  name: deploy_view_user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: deploy_view_user
  apiGroup: rbac.authorization.k8s.io
